// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDyZTwZmlIn2H6gKkdaghQ7zpKJqykpQU',
    appId: '1:384104181408:web:125cb971f403db9dac23c5',
    messagingSenderId: '384104181408',
    projectId: 'todo-list-1dd5f',
    authDomain: 'todo-list-1dd5f.firebaseapp.com',
    storageBucket: 'todo-list-1dd5f.appspot.com',
    measurementId: 'G-89KBXGRLDR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASzVmZ_G7pUqFyrANoNRkR61acxzoyRCQ',
    appId: '1:384104181408:android:5eb13de1d8133a1fac23c5',
    messagingSenderId: '384104181408',
    projectId: 'todo-list-1dd5f',
    storageBucket: 'todo-list-1dd5f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0bpywxzPCUKVBiv43Qi9THlzyNqOilUM',
    appId: '1:384104181408:ios:ffc510380726b3a1ac23c5',
    messagingSenderId: '384104181408',
    projectId: 'todo-list-1dd5f',
    storageBucket: 'todo-list-1dd5f.appspot.com',
    iosBundleId: 'com.example.todoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0bpywxzPCUKVBiv43Qi9THlzyNqOilUM',
    appId: '1:384104181408:ios:ffc510380726b3a1ac23c5',
    messagingSenderId: '384104181408',
    projectId: 'todo-list-1dd5f',
    storageBucket: 'todo-list-1dd5f.appspot.com',
    iosBundleId: 'com.example.todoList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDyZTwZmlIn2H6gKkdaghQ7zpKJqykpQU',
    appId: '1:384104181408:web:4996b6600a9fdc42ac23c5',
    messagingSenderId: '384104181408',
    projectId: 'todo-list-1dd5f',
    authDomain: 'todo-list-1dd5f.firebaseapp.com',
    storageBucket: 'todo-list-1dd5f.appspot.com',
    measurementId: 'G-YBC3VHXZX3',
  );
}
